### PR TITLE
Updated Meetup Details

### PR DESCRIPTION
**Pull request by chrishough**
For the meeting Tuesday and moving forward. Thank you.

### CODE REVIEW

**Review by Valarissa — APPROVED** [review]

**Review by Valarissa — CHANGES_REQUESTED** [review]
Where and when is the meetup going to be now? Or is that up in the air?

**Comment by chrishough** [comment]
Still at Airbnb for one of the meetings, however, we are going to be running multiple meetings. So instead of having multiple slides, I would like to defer to twitter and our website for the primary source of record.  Other groups in town work the same way 😸

**Comment by chrishough** [comment]
We have already moved away from this format in favor of other formats i.e. ::  http://monthly.preshow.rubyonrailspdx.org/#/3  - it gives other groups freedom to adjust their schedules and we do not display errors since we are not the owner of record.

**Comment by chrishough** [comment]
Thank you @Valarissa

**Pull request merged**
